### ISSUE TITLE
N8AO Named export 'Pass' not found

### ISSUE THREAD

**Issue by MrUltimate** [pmndrs/react-postprocessing#214] opened 2023-05-25 14:39 UTC
Hi!

I'm trying to use the new `<N8AO />` and running into the following issue:

```javascript
Server Error
SyntaxError: Named export 'Pass' not found. The requested module 'postprocessing' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'postprocessing';
const {Pass: $5Whe3$Pass1} = pkg;

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///Users/shivamsinha/Documents/Design_Work/Portfolio-2023/node_modules/n8ao/dist/N8AO.js (3)
ModuleJob._instantiate
node:internal/modules/esm/module_job (124:21)
async ModuleJob.run
node:internal/modules/esm/module_job (181:5)
async ESMLoader.import
node:internal/modules/esm/loader (281:24)
async importModuleDynamicallyWrapper
node:internal/vm/module (437:15)
```

**Comment by Carnageous** [comment] 2023-05-27 11:43
I had the same issue right now just by using `EffectComposer`. Downgrading to version 2.8.0 fixed it for me.
A blind guess of mine is that this was introduced when [upgrading to react 18](https://github.com/pmndrs/react-postprocessing/commit/203c6c319751478e2f063de3be3edf6ee08e1222). I am also using react v18, but in combination with Next.js which might be part of the issue.

If I manage to find a solution I'll let you know :)

**Comment by jakke-korpelainen** [comment] 2023-05-27 15:30
+1 Same issue here.

**Comment by CodyJasonBennett** [comment] 2023-05-27 15:57
The `n8ao` package is misconfigured and interpreted as commonJS even though it uses ESM syntax and dependencies. I can quickly fix this here by bundling/transpiling ourselves alongside the library.

**Comment by drcmda** [comment] 2023-05-27 18:45
@CodyJasonBennett @N8python can this also be addressed in the n8ao lib directly? then we can shed our fix

**Closed** 2023-05-27 18:45 UTC

**Comment by CodyJasonBennett** [comment] 2023-05-27 18:53
Looking into a proper fix. Latest N8AO specifies `type=module` so it is configured correctly for Node. Maybe it needs `module="./dist/N8AO.js"` for Webpack/Next? In any case, being ESM-only would require us to either dynamically import the library or vendor/transpile all the same.

**Comment by talentlessguy** [comment] 2023-05-27 18:55
@CodyJasonBennett i'm not the expert but i think next.js supports native esm. i think the deps mighr have incorrect package.json

**Comment by CodyJasonBennett** [comment] 2023-05-27 19:00
It does but the problem is that N8AO (ESM) is loading a CJS version of postprocessing, so Next may not be understanding Node resolution here. I only know of Webpack 4 which doesn't understand Node resolution at all.

**Comment by jakke-korpelainen** [comment] 2023-05-28 16:26
After installing @latest a new problem appeared.

SyntaxError: Named export 'BlendFunction' not found. The requested module 'postprocessing' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'postprocessing';
const { EffectComposer: EffectComposer$1, RenderPass, NormalPass, DepthDownsamplingPass, Effect, EffectPass, Pass, DepthOfFieldEffect, MaskFunction, DepthPickingPass, CopyPass, BlendFunction, BloomEffect, BrightnessContrastEffect, ChromaticAberrationEffect, ColorAverageEffect, ColorDepthEffect, DepthEffect, DotScreenEffect, GlitchEffect, GlitchMode, GodRaysEffect, GridEffect, HueSaturationEffect, NoiseEffect, OutlineEffect, PixelationEffect, ScanlineEffect, SelectiveBloomEffect, SepiaEffect, SSAOEffect, SMAAEffect, FXAAEffect, TextureEffect, ToneMappingEffect, VignetteEffect, ShockWaveEffect, LUT3DEffect, TiltShiftEffect: TiltShiftEffect$1, EffectAttribute } = pkg;

**Comment by CodyJasonBennett** [comment] 2023-05-28 16:46
Can you share a repo?

**Comment by jsellam** [comment] 2023-06-02 07:42
> BlendFunction



> SyntaxError: Named export 'BlendFunction' not found.

I have the same issue

**Comment by jakke-korpelainen** [comment] 2023-06-02 08:15
> Can you share a repo?

Tried isolating the issue here
https://github.com/jakke-korpelainen/blendfunction-issue-repro/blob/main/src/app/page.tsx'

But it works now so this might be a problem in my project with some older version of next.
